# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ed7a768976475e4c984bc8c3f8a0793512efce5738525685f3bf287111920b949c56a280b2b23fb8a9c456d1ec85bf98f655ab08b84d35948638835854bcd88

test:
  secret_key_base: aabb3c550f403d320728efa9ece238551ee3d1a07a65b6809286de813c213de3edd7f5e9dfad088d89b59a9506be4a47076a4b43e1077e148ec3d0586e61cf0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
